### ISSUE TITLE
Filtering   "lambda p: p.requires_grad, self.net.parameters()"

### ISSUE THREAD

**Issue by diff7** [feidfoe/learning-not-to-learn#3]
Hi, awesome project, thank you!

I was wondering why do you filter here?
Maybe I missed something.

self.optim = optim.SGD(filter(lambda p: p.requires_grad, self.net.parameters())

**Comment by feidfoe** [comment]
In this code, you don't have to do the filtering.
It is simply my routine for code robustness.

Thanks.
-Byungju Kim

**Comment by diff7** [comment]
Got it, thank you!
